version: "3"



services:
  postgresdb:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DBNAME}
    ports:
      - "5432:5432"
 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["/code/backend/wait-for-it.sh", "db:5432", "--", "sh", "/code/backend/script.sh"]
    ports:
      - 8010:8010
    volumes:
      - .:/code/
    depends_on:
      - postgresdb
  
  nginx:
    image: nginx:1.19.10
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/movies_admin/config/static:/data/static
    depends_on:
      - backend
    ports:
      - "80:80"
