# Generated by Django 3.1 on 2021-05-12 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('plot', models.TextField(blank=True, null=True, verbose_name='содержание')),
                ('imdb_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='рейтинг')),
            ],
            options={
                'verbose_name': 'кинопроизведение',
                'verbose_name_plural': 'кинопроизведения',
                'db_table': 'film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'человек',
                'verbose_name_plural': 'люди',
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='FilmWorkPerson',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('person_type', models.CharField(choices=[('Actor', 'актер'), ('Director', 'режиссёр'), ('Writer', 'сценарист')], max_length=30, verbose_name='профессия')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filmwork_person', to='movies.filmwork')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person')),
            ],
            options={
                'db_table': 'film_work_person',
            },
        ),
        migrations.CreateModel(
            name='FilmWorkGenre',
            fields=[
                ('film_work', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='filmwork_genre', serialize=False, to='movies.filmwork')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='genre', to='movies.genre')),
            ],
            options={
                'db_table': 'film_work_genre',
                'unique_together': {('film_work', 'genre')},
            },
        ),
    ]
