# Generated by Django 3.1 on 2021-05-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210512_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='genres',
            new_name='genres_id',
        ),
        migrations.RenameField(
            model_name='filmwork',
            old_name='persons',
            new_name='persons_id',
        ),
    ]
